# Generated by Django 3.2.13 on 2022-05-21 05:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tree_sitter_server', '0002_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 21, 5, 45, 56, 307090, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
