# Generated by Django 3.2.13 on 2022-05-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_sitter_server', '0004_search_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='language',
            field=models.CharField(default='python', max_length=100),
            preserve_default=False,
        ),
    ]
