# Generated by Django 3.2.13 on 2022-05-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syntaxforest', '0007_auto_20220524_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=4096)),
                ('sha', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='language',
            field=models.CharField(default='python', max_length=100),
            preserve_default=False,
        ),
    ]
