# Generated by Django 3.2.13 on 2022-05-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree_sitter_server', '0009_auto_20220529_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='end_byte',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capture',
            name='end_point_col',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capture',
            name='end_point_row',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capture',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capture',
            name='start_byte',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capture',
            name='start_point_col',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='capture',
            name='start_point_row',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
