# Generated by Django 3.2.13 on 2022-05-24 02:53

import modelqueue
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syntaxforest', '0005_search_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='status',
            field=models.BigIntegerField(
                db_index=True, default=modelqueue.Status.waiting
            ),
        ),
    ]
