# Generated by Django 3.2.13 on 2022-05-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syntaxforest', '0006_search_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='source',
        ),
        migrations.AddField(
            model_name='source',
            name='sha',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='source',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='source',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='path',
            field=models.CharField(max_length=4096, unique=True),
        ),
    ]
