# Generated by Django 3.2.13 on 2022-05-29 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syntaxforest', '0008_auto_20220528_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capture',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='capture',
            name='path',
        ),
        migrations.RemoveField(
            model_name='capture',
            name='sha',
        ),
        migrations.AddField(
            model_name='search',
            name='progress',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('path', models.CharField(max_length=4096, unique=True)),
                ('sha', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(blank=True)),
                ('language', models.CharField(max_length=100)),
                (
                    'search',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='syntaxforest.search',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='capture',
            name='result',
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to='syntaxforest.result',
            ),
            preserve_default=False,
        ),
    ]
