# Generated by Django 3.2.13 on 2022-05-29 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syntaxforest', '0011_alter_result_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capture',
            old_name='end_point_row',
            new_name='end_point_line',
        ),
        migrations.RenameField(
            model_name='capture',
            old_name='start_point_row',
            new_name='start_point_line',
        ),
    ]
