# Generated by Django 3.2.13 on 2023-06-27 05:47

from django.db import migrations, models
import django.db.models.deletion
import modelqueue


class Migration(migrations.Migration):

    dependencies = [
        ('syntaxforest', '0012_auto_20220529_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='progress',
        ),
        migrations.AddField(
            model_name='search',
            name='search_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='search',
            name='source_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BigIntegerField(db_index=True, default=modelqueue.Status.waiting)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syntaxforest.search')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syntaxforest.source')),
            ],
        ),
    ]
