name: release

on:
  push:
    tags:
      - v*

jobs:

  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.4'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create source dist
        run: python setup.py sdist

      - name: Create wheel dist
        run: python setup.py bdist_wheel

      - name: Upload with twine
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: twine upload dist/*

  update:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # # Dokku Setup Notes
      #
      # ## Domain Config
      #
      # $ ssh dokku@syntaxforest.com domains:add syntaxforest syntaxforest.com
      # $ ssh dokku@syntaxforest.com domains:add syntaxforest www.syntaxforest.com
      # $ ssh dokku@syntaxforest.com redirect:set syntaxforest www.syntaxforest.com syntaxforest.com
      #
      #
      # ## Database Config
      #
      # ssh dokku@syntaxforest.com postgres:create postgres143-syntaxforest -I 14.3
      # ssh dokku@syntaxforest.com postgres:link postgres143-syntaxforest syntaxforest
      #
      #
      # ## SSL Config
      #
      # ssh dokku@syntaxforest.com config:set --no-restart syntaxforest DOKKU_LETSENCRYPT_EMAIL=webmaster@syntaxforest.com
      # ssh dokku@syntaxforest.com letsencrypt syntaxforest

      - name: Push to syntaxforest.com
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@syntaxforest.com:22/syntaxforest'
          ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
